version: '3.1'

services:
  # consignment-cli:
  #   build: ./consignment-cli
  #   environment:
  #     MICRO_REGISTRY: "mdns"
  #   depends_on:
  #     - consignment-service

  consignment-service:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"
    depends_on:
      - datastore

  vessel-service:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"
    depends_on:
      - datastore

  # auth-cli:
  #   build: ./auth-cli
  #   environment:
  #     MICRO_REGISTRY: "mdns"
  #   depends_on:
  #     - auth-service

  auth-service:
    build: ./auth-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - database

  email-service:
    build: ./email-service
    ports:
      - 50054:50054
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"

  api:
    image: microhq/micro:latest
    command: --registry_address=consul:8500 api --handler=rpc --address=:8080 --namespace=shippy
    ports:
      - 8080:8080
    environment:
      MICRO_REGISTRY: "mdns"

  datastore:
    image: mongo
    ports:
      - 27017:27017

  database:
    image: postgres
    ports:
      - 5432:5432
