// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consignment/consignment.proto

package consignment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Consignment struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32        `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_15c28d78576246af, []int{0}
}
func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (dst *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(dst, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_15c28d78576246af, []int{1}
}
func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (dst *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(dst, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_15c28d78576246af, []int{2}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	Created              bool           `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignment          *Consignment   `protobuf:"bytes,2,opt,name=consignment,proto3" json:"consignment,omitempty"`
	Consignments         []*Consignment `protobuf:"bytes,3,rep,name=consignments,proto3" json:"consignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_15c28d78576246af, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func (m *Response) GetConsignments() []*Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

func init() {
	proto.RegisterType((*Consignment)(nil), "consignment.Consignment")
	proto.RegisterType((*Container)(nil), "consignment.Container")
	proto.RegisterType((*Request)(nil), "consignment.Request")
	proto.RegisterType((*Response)(nil), "consignment.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ConsignmentService service

type ConsignmentServiceClient interface {
	Create(ctx context.Context, in *Consignment, opts ...client.CallOption) (*Response, error)
	Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type consignmentServiceClient struct {
	c           client.Client
	serviceName string
}

func NewConsignmentServiceClient(serviceName string, c client.Client) ConsignmentServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "consignment"
	}
	return &consignmentServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *consignmentServiceClient) Create(ctx context.Context, in *Consignment, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ConsignmentService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consignmentServiceClient) Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ConsignmentService.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ConsignmentService service

type ConsignmentServiceHandler interface {
	Create(context.Context, *Consignment, *Response) error
	Get(context.Context, *Request, *Response) error
}

func RegisterConsignmentServiceHandler(s server.Server, hdlr ConsignmentServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&ConsignmentService{hdlr}, opts...))
}

type ConsignmentService struct {
	ConsignmentServiceHandler
}

func (h *ConsignmentService) Create(ctx context.Context, in *Consignment, out *Response) error {
	return h.ConsignmentServiceHandler.Create(ctx, in, out)
}

func (h *ConsignmentService) Get(ctx context.Context, in *Request, out *Response) error {
	return h.ConsignmentServiceHandler.Get(ctx, in, out)
}

func init() {
	proto.RegisterFile("proto/consignment/consignment.proto", fileDescriptor_consignment_15c28d78576246af)
}

var fileDescriptor_consignment_15c28d78576246af = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x3b, 0x4e, 0x03, 0x31,
	0x10, 0x65, 0xb3, 0xf9, 0xed, 0x2c, 0xa2, 0x18, 0x41, 0xb0, 0xa0, 0x60, 0xb5, 0x34, 0xa9, 0x82,
	0x14, 0x10, 0x05, 0xd0, 0xa5, 0x40, 0x69, 0xcd, 0x01, 0x50, 0xb0, 0x47, 0xc1, 0x12, 0xb1, 0x83,
	0xed, 0x84, 0x23, 0x70, 0x0b, 0x4e, 0xc0, 0x21, 0x51, 0xbc, 0x59, 0x70, 0x82, 0xb6, 0x9b, 0xf7,
	0xde, 0x3c, 0xcf, 0x9b, 0x91, 0xe1, 0x72, 0x69, 0x8d, 0x37, 0x57, 0xc2, 0x68, 0xa7, 0xe6, 0x7a,
	0x41, 0xda, 0xc7, 0xf5, 0x28, 0xa8, 0x98, 0x47, 0x54, 0xf9, 0x9d, 0x40, 0x3e, 0xf9, 0xc3, 0x78,
	0x04, 0x2d, 0x25, 0x59, 0x52, 0x24, 0xc3, 0x8c, 0xb7, 0x94, 0xc4, 0x02, 0x72, 0x49, 0x4e, 0x58,
	0xb5, 0xf4, 0xca, 0x68, 0xd6, 0x0a, 0x42, 0x4c, 0xe1, 0x00, 0xba, 0x1f, 0xa4, 0xe6, 0xaf, 0x9e,
	0xa5, 0x45, 0x32, 0xec, 0xf0, 0x2d, 0xc2, 0x5b, 0x00, 0x61, 0xb4, 0x9f, 0x29, 0x4d, 0xd6, 0xb1,
	0x76, 0x91, 0x0e, 0xf3, 0xf1, 0x60, 0x14, 0xc7, 0x99, 0xd4, 0x32, 0x8f, 0x3a, 0xf1, 0x1c, 0xb2,
	0x35, 0x39, 0x47, 0x6f, 0xcf, 0x4a, 0xb2, 0x4e, 0x98, 0xd7, 0xaf, 0x88, 0xa9, 0x2c, 0x17, 0x90,
	0xfd, 0xba, 0xfe, 0x65, 0xbd, 0x80, 0x5c, 0xac, 0x9c, 0x37, 0x0b, 0xb2, 0x1b, 0x6f, 0x95, 0x15,
	0x6a, 0x6a, 0x2a, 0x37, 0x51, 0x8d, 0x55, 0x73, 0xa5, 0x43, 0xd4, 0x8c, 0x6f, 0x11, 0x9e, 0x42,
	0x6f, 0xe5, 0x2a, 0x53, 0xbb, 0x12, 0x36, 0x70, 0x2a, 0xcb, 0x0c, 0x7a, 0x9c, 0xde, 0x57, 0xe4,
	0x7c, 0xf9, 0x95, 0x40, 0x9f, 0x93, 0x5b, 0x1a, 0xed, 0x08, 0x19, 0xf4, 0x84, 0xa5, 0x99, 0xa7,
	0x6a, 0x7c, 0x9f, 0xd7, 0x10, 0xef, 0x20, 0x3e, 0x6f, 0xc8, 0x90, 0x8f, 0xd9, 0xfe, 0xda, 0x75,
	0xcd, 0xe3, 0x66, 0x7c, 0x80, 0xc3, 0x08, 0x3a, 0x96, 0x86, 0x9b, 0x35, 0x9b, 0x77, 0xba, 0xc7,
	0x9f, 0x09, 0x60, 0xa4, 0x3e, 0x91, 0x5d, 0x2b, 0x41, 0x78, 0x0f, 0xdd, 0x49, 0xc8, 0x86, 0x8d,
	0x0f, 0x9d, 0x9d, 0xec, 0x28, 0xf5, 0x96, 0xe5, 0x01, 0xde, 0x40, 0xfa, 0x48, 0x1e, 0x8f, 0xf7,
	0xf4, 0x70, 0x91, 0x46, 0xd7, 0x4b, 0x37, 0xfc, 0xb3, 0xeb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x13, 0xc5, 0xc9, 0xb6, 0x8e, 0x02, 0x00, 0x00,
}
